name: 'Deploy Ecspresso'
description: 'Deploy ECS with Ecspresso'
author: hello@cloudposse.com
branding:
  icon: 'search'
  color: 'white'
inputs:
  image:
    description: Docker image
    required: true
  image-tag:
    description: Docker image tag
    required: true
  debug:
    description: Debug mode
    default: 'false'
    required: false
  region:
    description: AWS Region
    required: true
  operation:
    description: Operation (valid options - `deploy`, `destroy`)
    required: true
    default: deploy
  cluster:
    description: Cluster name
    required: true
  ecspresso-version:
    description: Ecspresso version
    required: false
    default: v2.1.0
  application:
    description: Application name
    required: true
  taskdef-path:
    description: Task definition path
    required: true
  timeout:
    description: Ecspresso timeout
    required: false
    default: 5m
  mirror_to_s3_bucket:
    description: Mirror task definition to s3 bucket
    required: false

outputs:
  webapp-url:
    description: "Web Application url"
    value: 'null'
          # https://${{ steps.webapp.outputs.output }}


runs:
  using: "composite"
  steps:
    - name: 'Install jq 1.6'
      uses: dcarbone/install-jq-action@v1.0.1
      with:
        version: 1.6
        force: 'true'

    - uses: kayac/ecspresso@v2
      with:
        version: ${{ inputs.ecspresso-version }}

    - uses: 1arp/create-a-file-action@0.2
      with:
        path: './'
        file: 'ecspresso.yml'
        content: |
          region: ${{ inputs.region }}
          cluster: ${{ inputs.cluster }}
          service: ${{ inputs.application }}
          task_definition: ${{ inputs.taskdef-path }}
          timeout: ${{ inputs.timeout }}

    - name: Deploy
      if: ${{ inputs.operation == 'deploy' }}
      shell: bash
      run: |
        ecspresso --config=./ecspresso.yml deploy
      env:
        IMAGE: ${{ inputs.image }}:${{ inputs.image-tag }}
        AWS_REGION: ${{ inputs.region }}

    - name: Set random environment variables
      if: ${{ inputs.operation == 'deploy' && inputs.mirror_to_s3_bucket != '' }}
      id: tmp
      shell: bash
      run: |
        VALUE=$(echo $RANDOM | md5sum | head -c 20)
        echo "dir_name=${VALUE}" >> $GITHUB_OUTPUT

    - name: Create TMP dir
      if: ${{ inputs.operation == 'deploy' && inputs.mirror_to_s3_bucket != '' }}
      shell: bash
      run: |
        mkdir ./${{ steps.tmp.outputs.dir_name }}

    - name: S3 mirroring
      if: ${{ inputs.operation == 'deploy' && inputs.mirror_to_s3_bucket != '' }}
      shell: bash
      run: |
        ecspresso --config=./ecspresso.yml render task-definition > ./${{ steps.tmp.outputs.dir_name }}/${{ inputs.application }}.json
      env:
        IMAGE: ${{ inputs.image }}:${{ inputs.image-tag }}
        AWS_REGION: ${{ inputs.region }}

    - name: Mirror task definition on S3
      if: ${{ inputs.operation == 'deploy' && inputs.mirror_to_s3_bucket != '' }}
      id: s3
      uses: zdurham/s3-upload-github-action@master
      env:
        FILE: ./${{ steps.tmp.outputs.dir_name }}/${{ inputs.application }}.json
        S3_BUCKET: ${{ inputs.mirror_to_s3_bucket }}
        S3_KEY: ${{ inputs.cluster }}/${{ inputs.application }}/task-definition.json

    - name: Cleanup TMP dir
      if: ${{ inputs.operation == 'deploy' && inputs.mirror_to_s3_bucket != '' }}
      shell: bash
      run: |
        rm -rf ./${{ steps.tmp.outputs.dir_name }}
