name: Test example negative
on:
  #  # Uncomment when test added first time to register workflow and comment it back after workflow would be registered
  #  #
  #  # Added pull_request to register workflow from the PR.
  #  # Read more https://stackoverflow.com/questions/63362126/github-actions-how-to-run-a-workflow-created-on-a-non-master-branch-from-the-wo
  #  pull_request: {}
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: echo "Do setup"

  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: us-east-2
          role-to-assume: ${{ secrets.IAM_ROLE }}
          role-skip-session-tagging: true

      - uses: ./
        id: current
        with:
          image: 252494810635.dkr.ecr.us-east-2.amazonaws.com/cloudposse/example-app-on-ecs
          image-tag: latest
          region: us-east-2
          operation: deploy
          cluster: cplive-plat-ue2-sandbox
          application: cplive-plat-ue2-sandbox-example
          taskdef-path: ./test/taskdef.json

    outputs:
      result: "${{ steps.current.outcome }}"

  assert:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: 'failure'
          actual: "${{ needs.test.outputs.result }}"

  teardown:
    runs-on: ubuntu-latest
    needs: [assert]
    if: ${{ always() }}
    steps:
      - name: Tear down
        run: echo "Do Tear down"
